# Generated by Django 5.0.3 on 2024-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructora_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
